name: Github Action CI

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/auto-twitter-profile-generater:latest

jobs:
  update_description:
    name: Update description
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.IMAGE_NAME }}
          run: python description.py
