name: Github Action CI

on:
  push:
    branches: [ master ]
env:
  # IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/auto-twitter-profile-generater:latest
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/auto-twitter-profile-generater:${{ github.run_number }}

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/auto-twitter-profile-generater:latest
          file: Dockerfile
